package com.example.utility;

import com.example.R;

public class FamousTechnologistsData {
	
	public static String TECHNOLOGIST1_NAME = "Shuchi Mukherjee";
	public static String TECHNOLOGIST1_DESIGNATION = "LimeRoad-ceo";
	public static int TECHNOLOGIST1_IMAGE = R.drawable.shuchimukherjee;
	public static String TECHNOLOGIST1_BACKGROUND = "Suchi is the founder and CEO of the online social discovery platform for women, LimeRoad. She is extremely passionate about building consumer technology products. With LimeRoad, she has an aim of revolutionizing the way lifestyle products are discovered and bought by people online in India. Before founding LimeRoad.com, Suchi have worked with companies like Skype, Gumtree, eBay and Virgin Media. Suchi post graduated from London School of Economics and graduated from St. Stephen’s College, Delhi.  In his life Suchi received many awards and recognition like K.C. Nag Economics Prize for best student in Economics, George K. George Memorial Scholarship for overall contribution, all at St. Stephen’s College, Delhi University, Cambridge Commonwealth Trust, Scholarship & Fellowship, and Chadburn Scholarship for merit, both at Cambridge University and British Chevening Scholarship, at the London School of Economics.";
	public static String TECHNOLOGIST1_CURRENT_OPENINGS = "1.) Intern- Front End development.\n 2.) Software developer - Python \n Feel free to send email to abc@limeroad.com";
	
	public static String TECHNOLOGIST2_NAME = "Anu Sridharan";
	public static String TECHNOLOGIST2_DESIGNATION = "NextDrop-founder";
	public static int TECHNOLOGIST2_IMAGE = R.drawable.anusridharan;
	public static String TECHNOLOGIST2_BACKGROUND = "Anu is the founder of NextDrop, a company which allows Indian residents in the urban areas to track the availability of piped water through SMS. The company already serves around 18,000 people in Karnataka. Anu has Bachelors in Civil Engineering and a Masters in Civil Systems Engineering from the University of California, Berkeley to her credit. She is determined to change the way in which technology allows us to interact with our urban systems. NextDrop began by tackling the problem of erratic water supply – in most of urban India, water is available only a few hours at a time or a few times a week, but residents have no way of knowing when. Working with operators in the field, NextDrop sends text messages 60 minutes before water arrives in your tap, while also offering utility boards the tools to better manage and track leakages in water supply. Anu holds her Bachelor’s and Master’s degrees from the Civil and Environmental Engineering program at the University of California, Berkeley, where her Master’s research focused on the optimization of piped networked systems in developing economies. Anu also served as the Education and Health director for a water/sanitation project in the slums of Mumbai, India called “Haath Mein Sehat”, where she piloted a successful volunteer recruitment and community-training model.Anu Sridharan was 23 years old when she became CEO of social startup NextDrop in Hubli- a town some 500 kilometers from Bangalore in Karnataka. Anu has also been selected to the Forbes \"30 Social Entrepreneurs Under 30\" list.";
	public static String TECHNOLOGIST2_CURRENT_OPENINGS = "1.) Intern- Front End development.\n 2.) Software developer - Python \n 3.) Civil Engineers - Intern and Full time. \n Send resumes to xyz@nextdrop.in";
	
	public static String TECHNOLOGIST3_NAME = "Ajaita Shah";
	public static String TECHNOLOGIST3_DESIGNATION = "Frontier Markets-founder & CEO";
	public static int TECHNOLOGIST3_IMAGE = R.drawable.ajaitashah;
	public static String TECHNOLOGIST3_BACKGROUND = "Ajaita is the founder and CEO of Frontier Markets started in 2009 by focusing on energy products and connecting with a microfinance partner in Karnataka. She has a goal of making high quality, affordable products and goods available to rural India. She has an experience of over 5 years in Microfinance with esteemed organizations like Ujjivan Financial Services and SKS Microfinance behind her back. Ajaita was also awarded with the title of being the most influential leader under 30 in microfinance by Business Week, and  Business Week’s 30 under 30 award, and most recently, Forbes Magazine’s Top 30 Under 30’s Social Entrepreneur of the Year. Her company Frontier Markets has an aim to be the scale solution for manufacturers creating goods for the rural markets of India. Ajaita trains locals to educate and sell to rural households. The company has sold 10,000 solar solutions to date. ";
	public static String TECHNOLOGIST3_CURRENT_OPENINGS = "1.) Full time - UI/UX developer.\n 2.) Intern- Content writer \n 3.) Full time and intern- photgraphers. Feel free to send your resumes to abc123@frontierm.com";
	
	public static String TECHNOLOGIST4_NAME = "Saloni Malhotra";
	public static String TECHNOLOGIST4_DESIGNATION = "Frontier DesiCrew";
	public static int TECHNOLOGIST4_IMAGE = R.drawable.salonimalhotra;
	public static String TECHNOLOGIST4_BACKGROUND = "Saloni is the founder of DesiCrew, which is an organization with over 300 employees who are focused and determined to create knowledge based livelihood or employment opportunities in rural areas and small towns. Saloni did her engineering from University of Pune in state of Maharashtra. She started her career in an interactive media start up, Web Chutney based in Delhi. She somehow came into contact of Professor Jhunjhunwala of TeNet group, IIT Madras and came up with this idea of founding DesiCrew. She stepped down as the CEO of DesiCrew in March 2012 and handed over her duties to a professional management team but she continues to be a part of the board. Saloni also co-founded Safecity in 2012 which is a citizen’s initiative to make Indian Cities safer again. Desicrew now has now four rural offices — Udupi, Apakoodal and Kollumangudi and employs 300-odd people from these villages. She has been nominated for Business Week Asia’s Best Youngest Entrepreneurs, MTV Youth Icon 2008, E&Y Entrepreneur of the Year 2008 and also facilitated in the presence of the President of India by the CII. She is the recipient of FICCI’s Best Women Social Entrepreneur Award (2009) and TIE Stree Shakthi Award (2011).";
	public static String TECHNOLOGIST4_CURRENT_OPENINGS = "1.) Intern- Front End development.\n 2.) Software developer - Python \n Feel free to send email to saloniMalhotra@desicrew.in";
}
